services:
  - type: web
    name: redirect-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app_db:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: redirect-db
          property: connectionString

databases:
  - name: redirect-db
